version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.3
    - 5.10.4
  - dependency-name: "@nestjs/testing"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@nestjs/platform-express"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@nestjs/cli"
    versions:
    - 7.5.4
    - 7.5.5
    - 7.5.6
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: "@types/supertest"
    versions:
    - 2.0.10
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
